// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/services": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/internship": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/projects" | "/projects/:id" | "/services" | "/about" | "/contact" | "/internship";
  };
  "../src/pages/Home.jsx": {
    id: "../src/pages/Home";
    page: "/";
  };
  "../src/pages/Projects.jsx": {
    id: "../src/pages/Projects";
    page: "/projects";
  };
  "../src/pages/ProjectDetail.jsx": {
    id: "../src/pages/ProjectDetail";
    page: "/projects/:id";
  };
  "../src/pages/Services.jsx": {
    id: "../src/pages/Services";
    page: "/services";
  };
  "../src/pages/About.jsx": {
    id: "../src/pages/About";
    page: "/about";
  };
  "../src/pages/Contact.jsx": {
    id: "../src/pages/Contact";
    page: "/contact";
  };
  "../src/pages/Internship.jsx": {
    id: "../src/pages/Internship";
    page: "/internship";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "../src/pages/Home": unknown;
  "../src/pages/Projects": unknown;
  "../src/pages/ProjectDetail": unknown;
  "../src/pages/Services": unknown;
  "../src/pages/About": unknown;
  "../src/pages/Contact": unknown;
  "../src/pages/Internship": unknown;
};