// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/photography": {
    params: {};
  };
  "/photography/:id": {
    params: {
      "id": string;
    };
  };
  "/services": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/projects" | "/projects/:id" | "/photography" | "/photography/:id" | "/services" | "/about" | "/contact";
  };
  "../src/pages/Home.jsx": {
    id: "../src/pages/Home";
    page: "/";
  };
  "../src/pages/Projects.jsx": {
    id: "../src/pages/Projects";
    page: "/projects";
  };
  "../src/pages/ProjectDetail.jsx": {
    id: "../src/pages/ProjectDetail";
    page: "/projects/:id";
  };
  "../src/pages/Photography.jsx": {
    id: "../src/pages/Photography";
    page: "/photography";
  };
  "../src/pages/PhotographyDetail.jsx": {
    id: "../src/pages/PhotographyDetail";
    page: "/photography/:id";
  };
  "../src/pages/Services.jsx": {
    id: "../src/pages/Services";
    page: "/services";
  };
  "../src/pages/About.jsx": {
    id: "../src/pages/About";
    page: "/about";
  };
  "../src/pages/Contact.jsx": {
    id: "../src/pages/Contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "../src/pages/Home": unknown;
  "../src/pages/Projects": unknown;
  "../src/pages/ProjectDetail": unknown;
  "../src/pages/Photography": unknown;
  "../src/pages/PhotographyDetail": unknown;
  "../src/pages/Services": unknown;
  "../src/pages/About": unknown;
  "../src/pages/Contact": unknown;
};